const express = require('express');
const bodyParser = require('body-parser');
const mysql = require("mysql");
const cors = require("cors");
require('dotenv').config();
const app = express();
app.use(cors());
app.use(bodyParser.json());
app.use('/uploads', express.static('uploads'));


const sliderRoutes = require('./routes/sliderRoutes');
const serviceRoutes = require('./routes/serviceRoutes');
const firestationRoutes = require('./routes/firestationRoutes');
const historyRoutes = require('./routes/historyRoutes');
const ceoRoutes = require('./routes/ceoRoutes');
const electedRoutes = require('./routes/electedRoutes');
const chiefRoutes = require('./routes/chiefRoutes');
const presidentRoutes = require('./routes/presidentRoutes');
const videosRoutes = require('./routes/videosRoutes');
const galleryRoutes = require('./routes/galleryRoutes');
const schoolRoutes = require('./routes/schoolRoutes');
const schoolImageRoutes = require('./routes/schoolImageRoutes');
const tenderRoutes = require('./routes/tenderRoutes');
const departmentRoutes = require('./routes/departmentRoutes');
const propertyHolderRoutes = require('./routes/propertyHolderRoutes');
const muncipalRoutes = require('./routes/muncipalRoutes');
const electricRoutes = require('./routes/electricRoutes');
const roadsRoutes = require('./routes/roadsRoutes');
const wardsRoutes = require('./routes/wardsRoutes');
const gardenRoutes = require('./routes/gardenRoutes');
const righttoservicesRoutes = require ('./routes/righttoservicesRoutes');
const pdfRToSRoutes = require('./routes/pdfRToSRoutes');
const citizenCharterRoutes = require('./routes/citizenCharterRoutes');
const AwardRoutes = require('./routes/AwardRoutes');
const awardImageRoutes = require('./routes/awardImageRoutes');
const GeneraladminaddyearRoutes = require('./routes/GeneraladminaddyearRoutes');
const GeneraladmindepartmentRoutes = require('./routes/GeneraladmindepartmentRoutes');
const NewsupdateRoutes = require('./routes/NewsupdateRoutes');
const PublicdescriptionRoutes = require('./routes/PublicdescriptionRoutes');
const WebsitelinkRoutes = require('./routes/WebsitelinkRoutes');
const userRoutes = require('./routes/userRoutes');
const pondRoutes = require('./routes/pondRoutes');
const hospitalRoutes = require('./routes/hospitalRoutes');
const censusRoutes = require('./routes/censusRoutes');
const functionRoutes = require('./routes/functionRoutes');
const healthDeptRoutes = require('./routes/healthDeptRoutes');
const sanitationRoutes = require('./routes/sanitationRoutes');
const treatmentRoutes = require('./routes/treatmentRoutes');
const litigationRoutes = require('./routes/litigationRoutes');
const healthPhotoRoutes = require('./routes/healthPhotoRoutes');
const mainMenuRoutes = require('./routes/mainMenuRoutes');
const contactRoutes = require('./routes/contactRoutes');
const loginRoutes = require('./routes/loginRoutes');

app.use('/api', sliderRoutes);
app.use('/api', serviceRoutes);
app.use('/api', firestationRoutes);
app.use('/api', historyRoutes);
app.use('/api', ceoRoutes);
app.use('/api', electedRoutes);
app.use('/api', chiefRoutes);
app.use('/api', presidentRoutes);
app.use('/api', videosRoutes);
app.use('/api', galleryRoutes);
app.use('/api', schoolRoutes);
app.use('/api', schoolImageRoutes);
app.use('/api', tenderRoutes);
app.use('/api', departmentRoutes);
app.use('/api', propertyHolderRoutes);
app.use('/api', electricRoutes);
app.use('/api', roadsRoutes);
app.use('/api', muncipalRoutes);
app.use('/api', wardsRoutes);
app.use('/api', gardenRoutes);
app.use('/api', righttoservicesRoutes);
app.use('/api', pdfRToSRoutes);
app.use('/api', citizenCharterRoutes);
app.use('/api', AwardRoutes);
app.use('/api', GeneraladminaddyearRoutes);
app.use('/api', GeneraladmindepartmentRoutes);
app.use('/api', NewsupdateRoutes);
app.use('/api', PublicdescriptionRoutes);
app.use('/api', WebsitelinkRoutes);
app.use('/api', userRoutes);
app.use('/api', pondRoutes);
app.use('/api', hospitalRoutes);
app.use('/api', censusRoutes);
app.use('/api', functionRoutes);
app.use('/api', healthDeptRoutes);
app.use('/api', sanitationRoutes);
app.use('/api', treatmentRoutes);
app.use('/api', litigationRoutes);
app.use('/api', healthPhotoRoutes);
app.use('/api', mainMenuRoutes);
app.use('/api', awardImageRoutes);
app.use('/api', contactRoutes);
app.use('/api', loginRoutes);

const PORT = process.env.PORT || 5000;
app.listen(PORT, () => {
    console.log(`Server running on port ${PORT}`);
});